### ISSUE TITLE
Transcendance correction sheet 

### ISSUE THREAD

**Issue by Nours42** [jotavare/42-resources#12]
it's just reaaaaallly great, i do to make the same rofl

**Comment by jotavare** [comment]
im happy that you got rick rolled ahaha

**Comment by Nours42** [comment]
im happy too, that's reaaly a good joke :) the subject of transcendance have change recently and that's why i searching the correction sheet. But i think it's too early too find it on internet, we'll have to do the subject without this. like a adventure in the unknow :)
